# Dependencies

In [35]:
!kaggle competitions download -c house-prices-advanced-regression-techniques -p '../data/' --force

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/viktor/.kaggle/kaggle.json'
Downloading house-prices-advanced-regression-techniques.zip to ../data
100%|█████████████████████████████████████████| 199k/199k [00:00<00:00, 507kB/s]
100%|█████████████████████████████████████████| 199k/199k [00:00<00:00, 507kB/s]

In [40]:
!7z x ../data/house-prices-advanced-regression-techniques.zip -o../data/ -y

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=en_US.UTF-8 Threads:12 OPEN_MAX:1048576

Scanning the drive for archives:
  0M Scan ../dat                1 file, 203809 bytes (200 KiB)

Extracting archive: ../data/house-prices-advanced-regression-techniques.zip
--
Path = ../data/house-prices-advanced-regression-techniques.zip
Type = zip
Physical Size = 203809

    Everything is Ok

Files: 4
Size:       957390
Compressed: 203809

In [41]:
import pandas as pd 
from sklearn.model_selection import train_test_split

Bidejki test datasetot ne e ko sho trebat, mu falit *SalePrice* kolonata, deka sakat na submission da ti go proverat modelot, ke go splitnime inicijalniot train data vo test i train, so cel da ne preme submission postojano na kaggle.

In [42]:
train=pd.read_csv('../data/train.csv')
x_tr,x_tst,y_tr,y_tst=train_test_split(train.drop('SalePrice',axis=1),train['SalePrice'],test_size=.2,random_state=42)

In [43]:
tmp=pd.concat([x_tr,y_tr],axis=1)
tmp==train.loc[tmp.index]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
254,True,True,True,True,True,True,False,True,True,True,...,True,False,False,False,True,True,True,True,True,True
1066,True,True,True,True,True,True,False,True,True,True,...,True,False,False,False,True,True,True,True,True,True
638,True,True,True,True,True,True,False,True,True,True,...,True,False,True,False,True,True,True,True,True,True
799,True,True,True,True,True,True,False,True,True,True,...,True,False,True,False,True,True,True,True,True,True
380,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,True,True,True,True,True,True,False,True,True,True,...,True,False,False,False,True,True,True,True,True,True
1130,True,True,True,True,True,True,False,True,True,True,...,True,False,True,False,True,True,True,True,True,True
1294,True,True,True,True,True,True,False,True,True,True,...,True,False,False,False,True,True,True,True,True,True
860,True,True,True,True,True,True,False,True,True,True,...,True,False,True,False,True,True,True,True,True,True
1126,True,True,True,True,True,True,False,True,True,True,...,True,False,False,False,True,True,True,True,True,True

In [44]:
tmp['Alley'],train.loc[tmp.index,'Alley']

(254      NaN
 1066     NaN
 638      NaN
 799      NaN
 380     Pave
         ...
 1095     NaN
 1130     NaN
 1294     NaN
 860      NaN
 1126     NaN
 Name: Alley, Length: 1168, dtype: object,
 254      NaN
 1066     NaN
 638      NaN
 799      NaN
 380     Pave
         ...
 1095     NaN
 1130     NaN
 1294     NaN
 860      NaN
 1126     NaN
 Name: Alley, Length: 1168, dtype: object)

In [45]:
tmp_train=pd.concat([x_tr,y_tr],axis=1)
tmp_test=pd.concat([x_tst,y_tst],axis=1)

In [46]:
with open('../data/train.csv','w') as tr_file: 
    tmp_train.to_csv(path_or_buf=tr_file,index_label='Index')

In [47]:
tmp=pd.read_csv('../data/train.csv',index_col='Index')
(tmp==tmp_train).sample(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Index,,,,,,,,,,,,,,,,,,,,,
514,True,True,True,True,True,True,False,True,True,True,...,True,False,True,False,True,True,True,True,True,True
624,True,True,True,True,True,True,False,True,True,True,...,True,False,False,False,True,True,True,True,True,True

Ova false kaj Alley i MiscFeatures se dolzhit na faktot deka se nans.

In [48]:
with open('../data/test.csv','w') as tst_file:
    tmp_test.to_csv(path_or_buf=tst_file,index_label='Index')